package net.uk.onetransport.android.test.onetransporttest.tests;

import net.uk.onetransport.android.test.onetransporttest.tests.bucks.trafficspeed.BucksTrafficSpeedRetrieveTest;
import net.uk.onetransport.android.test.onetransporttest.tests.bucks.traffictraveltime.BucksTrafficTravelTimeRetrieveTest;

public class TestList {

    public OneTransportTest[] oneTransportTests = {
//            new ApplicationEntityCreateTest(),
//            new BucksCarParkRetrieveTest(),
//            new BucksEventRetrieveTest(),
//            new BucksRoadWorksRetrieveTest(),
//            new BucksTrafficFlowRetrieveTest(),
//            new BucksTrafficQueueRetrieveTest(),
//            new BucksTrafficScootRetrieveTest(),
//            new BucksTrafficSpeedRetrieveTest(),
            new BucksTrafficTravelTimeRetrieveTest()
//            new GetVariableMessageSignArrayTest(),
//            new GetTrafficFlowArrayTest(),
//            new GetRoadWorksArrayTest(),
//            new BucksCarParkDeleteTest(),
//            new BucksVariableMessageSignDeleteTest(),
//            new BucksTrafficFlowDeleteTest(),
//            new BucksRoadWorksDeleteTest(),
//            new BucksCarParkInsertTest(),
//            new BucksVariableMessageSignInsertTest(),
//            new BucksTrafficFlowInsertTest(),
//            new BucksRoadWorksInsertTest(),
//            new BucksVmsQueryTest(),
//            new BucksTrafficFlowQueryTest(),
//            new BucksCarParkBoxQueryTest(),
//            new BucksVmsBoxQueryTest(),
//            new BucksTrafficFlowBoxQueryTest(),
//            new BucksRoadWorksBoxQueryTest(),
//            new BucksSyncAdapterTest(),
            // Clearview Silverstone.
//            new DeviceRetrieveTest(),
//            new TrafficGroupRetrieveTest(),
//            new CvsDeviceDeleteTest(),
//            new CvsTrafficGroupDeleteTest(),
//            new CvsDeviceInsertTest(),
//            new CvsTrafficGroupInsertTest(),
//            new CvsDeviceQueryTest(),
//            new CvsTrafficGroupQueryTest(),
//            new CvsSyncAdapterTest(),
            // BitCarrier Silverstone
//            new BcsNodeRetrieveTest(),
//            new BcsNodeDeleteTest(),
//            new BcsNodeInsertTest(),
//            new BcsNodeQueryTest(),
//            new BcsNodeIntervalQueryTest(),
//            new BcsDataVectorRetrieveTest(),
//            new BcsDataVectorInsertTest(),
//            new BcsDataVectorDeleteTest(),
//            new BcsDataVectorInsertTest(),
//            new BcsDataVectorQueryTest(),
//            new BcsLatestDataVectorQueryTest(),
//            new BcsDataVectorIntervalQueryTest(),
//            new BcsDataVectorDeleteBeforeTest(),
//            new BcsConfigVectorRetrieveTest(),
//            new BcsConfigVectorDeleteTest(),
//            new BcsConfigVectorInsertTest(),
//            new BcsConfigVectorQueryTest(),
//            new BcsConfigVectorIntervalQueryTest(),
//            new BcsTravelSummaryRetrieveTest(),
//            new BcsTravelSummaryInsertTest(),
//            new BcsTravelSummaryDeleteTest(),
//            new BcsTravelSummaryInsertTest(),
//            new BcsTravelSummaryQueryTest(),
//            new BcsLatestTravelSummaryQueryTest(),
//            new BcsTravelSummaryIntervalQueryTest(),
//            new BcsTravelSummaryDeleteBeforeTest(),
//            new BcsSketchRetrieveTest(),
//            new BcsSketchDeleteTest(),
//            new BcsSketchInsertTest(),
//            new BcsSketchQueryTest(),
//            new BcsSketchIntervalQueryTest(),
//            new BcsSyncAdapterTest(),

//            new ApplicationEntityDeleteTest()
    };
}
